# Generated by Django 5.2.7 on 2025-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_subrole',
            field=models.CharField(blank=True, choices=[('dept_head_cs', 'CS Department Head'), ('dept_head_it', 'IT Department Head'), ('dean', 'Dean')], max_length=30, null=True),
        ),
    ]
