# Generated by Django 4.2.26 on 2025-11-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_admin_subrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, help_text='For students only (e.g., 3A, 2B) - used for auto-enrollment', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], help_text='For students only - used for auto-enrollment', null=True),
        ),
    ]
