from django.urls import path
from .views import (
    load_training_data,
    get_student_enrollments,
    submit_feedback,
    get_faculty_courses,
    get_feedback_analytics,
    get_emotion_analytics,
    get_topic_modeling_data,
    trigger_topic_modeling,
    get_available_years,
    export_feedback_pdf,
    get_courses_list,
    get_response_stats,
    get_sentiment_words,
    # Revision endpoints
    get_alignment_analysis,
    get_thematic_analysis,
    get_encoding_consistency,
    get_negative_course_summary,
    get_course_rating_extremes,
    get_ai_expert_comparison,
    get_visualization_summary,
)

urlpatterns = [
    path('preview-data/', load_training_data, name='preview_data'),
    path('enrollments/', get_student_enrollments, name='student_enrollments'),
    path('feedback/', submit_feedback, name='submit_feedback'),
    path('faculty/courses/', get_faculty_courses, name='faculty_courses'),
    path('feedback/analytics/', get_feedback_analytics, name='feedback_analytics'),
    path('feedback/available-years/', get_available_years, name='available_years'),
    path('feedback/courses/', get_courses_list, name='courses_list'),
    path('feedback/response-stats/', get_response_stats, name='response_stats'),
    path('feedback/export-pdf/', export_feedback_pdf, name='export_feedback_pdf'),
    path('feedback/sentiment-words/', get_sentiment_words, name='sentiment_words'),
    path('emotions/analytics/', get_emotion_analytics, name='emotion_analytics'),
    path('topics/', get_topic_modeling_data, name='topic_modeling'),
    path('topics/trigger/', trigger_topic_modeling, name='trigger_topic_modeling'),
    # Revision endpoints
    path('revision/alignment-analysis/', get_alignment_analysis, name='alignment_analysis'),
    path('revision/thematic-analysis/', get_thematic_analysis, name='thematic_analysis'),
    path('revision/encoding-consistency/', get_encoding_consistency, name='encoding_consistency'),
    path('revision/negative-summary/', get_negative_course_summary, name='negative_course_summary'),
    path('revision/course-rating-extremes/', get_course_rating_extremes, name='course_rating_extremes'),
    path('revision/ai-expert-comparison/', get_ai_expert_comparison, name='ai_expert_comparison'),
    path('revision/visualization-summary/', get_visualization_summary, name='visualization_summary'),
]
