# Generated by Django 4.2.26 on 2025-11-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CS101, IT202', max_length=20, unique=True)),
                ('name', models.CharField(help_text='e.g., Data Structures', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ICT', 'ICT')], max_length=5)),
                ('year_level', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('units', models.IntegerField(default=3, help_text='Credit units')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department', 'year_level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('section', models.CharField(blank=True, help_text='Leave blank to assign to all sections of this year level', max_length=10, null=True)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ICT', 'ICT')], max_length=5)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], max_length=10)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('schedule', models.CharField(blank=True, help_text='e.g., MWF 9:00-10:00 AM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.course')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Assignment',
                'verbose_name_plural': 'Course Assignments',
                'ordering': ['-academic_year', 'semester', 'course'],
                'unique_together': {('course', 'instructor', 'year_level', 'section', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., End of 1st Semester 2024-2025 Feedback', max_length=200)),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one session should be active at a time')),
                ('instructions', models.TextField(blank=True, help_text='Instructions to display to students when submitting feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback Session',
                'verbose_name_plural': 'Feedback Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Overall rating (1-5 stars)')),
                ('suggested_changes', models.TextField(blank=True, help_text='What changes would you suggest?')),
                ('best_teaching_aspect', models.TextField(blank=True, help_text='What did you like best about the teaching?')),
                ('least_teaching_aspect', models.TextField(blank=True, help_text='What did you like least?')),
                ('further_comments', models.TextField(blank=True, help_text='Any additional comments')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score from ML model (-1 to 1)', null=True)),
                ('sentiment_label', models.CharField(blank=True, help_text='e.g., Positive, Negative, Neutral', max_length=20)),
                ('emotions', models.JSONField(blank=True, help_text='Detected emotions from ML model (JSON)', null=True)),
                ('is_anonymous', models.BooleanField(default=True, help_text='Student identity is hidden from instructor')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.courseassignment')),
                ('feedback_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.feedbacksession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'course_assignment', 'feedback_session')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_enrolled', models.BooleanField(default=True, help_text='True if enrolled automatically, False if manually added (e.g., irregular student)')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.courseassignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course_assignment')},
            },
        ),
    ]
