# Generated by Django 4.2.26 on 2025-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'year_level', 'semester', 'code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Summer', 'Summer')], default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='e.g., CS101, IT202', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'department', 'year_level', 'semester')},
        ),
    ]
