# Generated by Django 4.2.26 on 2025-11-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_options_course_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating_availability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Makes self available to students after class session'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_learning_objectives',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Integrates learning objectives with students in a collaborative process'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_punctuality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Regularly comes to class on time, well-groomed and well-prepared'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_record_keeping',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text="Keeps accurate records of students' performance and prompt submission"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_sensitivity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text="Demonstrates sensitivity to students' ability to attend and absorb content"),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(blank=True, help_text='Overall average rating (computed from 5 rating questions)', null=True),
        ),
    ]
