# Generated by Django 4.2.26 on 2025-11-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback_rating_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating_learning_objectives',
        ),
        migrations.AddField(
            model_name='feedback',
            name='assignments_related',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='delivered_as_outlined',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='exams_related',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='grading_criteria_explained',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='hours_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='lms_resources_useful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_achieving_outcomes',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_beyond_required',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_clear_communication',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_constructive_contribution',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_current_trends',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_discussion_encouragement',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_facilitator_role',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_improvement_feedback',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_independent_thinking',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_instructional_materials',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_instructional_methods',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_integration',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Integrates learning objectives with students'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_mastery',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_practical_integration',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_relevance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_state_of_art',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_student_autonomy',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_student_contribution',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_student_esteem',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_teaching_strategies',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_timely_feedback',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='syllabus_explained',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='worthwhile_class',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='would_recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(blank=True, help_text='Overall average rating (computed from all rating questions)', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating_availability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Makes self available to students after class'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating_punctuality',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Comes to class on time, well-prepared'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating_record_keeping',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Keeps accurate records and prompt submission'),
        ),
    ]
