# Generated by Django 4.2.26 on 2025-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_feedback_rating_learning_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emotion_best_aspect',
            field=models.CharField(blank=True, help_text='Predicted emotion for best_teaching_aspect field', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='emotion_confidence_scores',
            field=models.JSONField(blank=True, help_text='Confidence scores for each emotion prediction', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='emotion_further_comments',
            field=models.CharField(blank=True, help_text='Predicted emotion for further_comments field', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='emotion_least_aspect',
            field=models.CharField(blank=True, help_text='Predicted emotion for least_teaching_aspect field', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='emotion_suggested_changes',
            field=models.CharField(blank=True, help_text='Predicted emotion for suggested_changes field', max_length=20),
        ),
    ]
