from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.piecharts import Pie
from io import BytesIO
from datetime import datetime
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from django.db.models import Avg, Count, Q

def generate_feedback_report_pdf(feedback_qs, filters, user):
    """Generate a comprehensive PDF report for feedback data"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter, 
        topMargin=0.5*inch, 
        bottomMargin=0.5*inch,
        leftMargin=0.75*inch,
        rightMargin=0.75*inch
    )
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor('#8E1B1B'),
        spaceAfter=8,
        spaceBefore=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=colors.HexColor('#8E1B1B'),
        spaceAfter=8,
        spaceBefore=10,
        fontName='Helvetica-Bold',
        borderWidth=0,
        borderColor=colors.HexColor('#8E1B1B'),
        borderPadding=4,
        backColor=colors.HexColor('#FFF5F5')
    )
    
    subheading_style = ParagraphStyle(
        'CustomSubHeading',
        parent=styles['Heading3'],
        fontSize=11,
        textColor=colors.HexColor('#555555'),
        spaceAfter=6,
        spaceBefore=8,
        fontName='Helvetica-Bold'
    )
    
    normal_style = styles['Normal']
    normal_style.fontSize = 10
    normal_style.leading = 14
    
    caption_style = ParagraphStyle(
        'Caption',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#666666'),
        spaceAfter=4,
        alignment=TA_CENTER,
        fontStyle='italic'
    )
    
    # Title
    if filters.get('instructor_name'):
        # Professor-specific report
        elements.append(Paragraph(f"Faculty Performance Evaluation Report", title_style))
        elements.append(Paragraph(f"Professor: {filters['instructor_name']}", ParagraphStyle(
            'ProfessorName',
            parent=styles['Normal'],
            fontSize=16,
            textColor=colors.HexColor('#8E1B1B'),
            alignment=TA_CENTER,
            spaceAfter=6,
            fontName='Helvetica-Bold'
        )))
        elements.append(Paragraph("AI-Powered Sentiment Analysis System", ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#666666'),
            alignment=TA_CENTER,
            spaceAfter=12
        )))
    else:
        # General report
        elements.append(Paragraph("Faculty Performance Evaluation Report", title_style))
        elements.append(Paragraph("AI-Powered Sentiment Analysis System", ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#666666'),
            alignment=TA_CENTER,
            spaceAfter=12
        )))
    elements.append(Spacer(1, 0.15*inch))
    
    # Report metadata in a clean box
    metadata = [
        ['Report Generated:', datetime.now().strftime('%B %d, %Y at %I:%M %p')],
        ['Generated By:', f"{user.first_name} {user.last_name}"],
        ['Department:', user.department or 'All Departments'],
    ]
    
    if filters.get('semester'):
        metadata.append(['Semester:', filters['semester'] + ' Semester'])
    if filters.get('academic_year'):
        metadata.append(['Academic Year:', filters['academic_year']])
    if filters.get('instructor_name'):
        metadata.append(['Instructor:', filters['instructor_name']])
    else:
        metadata.append(['Scope:', 'Overall Department Performance'])
    
    metadata_table = Table(metadata, colWidths=[1.8*inch, 4.7*inch])
    metadata_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#555555')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#000000')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F9FAFB')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E5E7EB')),
    ]))
    elements.append(metadata_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # Total feedback count with emphasis
    total_feedback = feedback_qs.count()
    summary_data = [
        ['Total Responses', str(total_feedback)],
        ['Response Rate', 'N/A'],  # Can be calculated if enrollment data available
    ]
    
    summary_table = Table(summary_data, colWidths=[3*inch, 3.5*inch])
    summary_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BACKGROUND', (1, 0), (1, -1), colors.HexColor('#8E1B1B')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.white),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (1, 0), (1, -1), 18),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E5E7EB')),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 0.15*inch))
    
    if total_feedback == 0:
        elements.append(Paragraph("No feedback data available for the selected filters.", normal_style))
        doc.build(elements)
        buffer.seek(0)
        return buffer
    
    # Executive Summary Section
    elements.append(Paragraph("1. Executive Summary", heading_style))
    
    # Aggregate ratings
    aggregates = feedback_qs.aggregate(
        avg_overall=Avg('overall_rating'),
        avg_commitment=Avg('rating_sensitivity'),
        avg_integration=Avg('rating_integration'),
        avg_availability=Avg('rating_availability'),
        avg_knowledge=Avg('rating_mastery'),
        avg_practical=Avg('rating_practical_integration'),
        avg_learning=Avg('rating_teaching_strategies'),
        avg_autonomy=Avg('rating_student_autonomy'),
        avg_management=Avg('rating_student_contribution'),
        avg_discussion=Avg('rating_discussion_encouragement'),
        avg_feedback_comm=Avg('rating_clear_communication'),
        avg_timely=Avg('rating_timely_feedback'),
        avg_student_contrib=Avg('rating_constructive_contribution'),
        avg_achieving=Avg('rating_achieving_outcomes'),
    )
    
    overall_avg = aggregates['avg_overall'] or 0
    
    # Performance interpretation
    if overall_avg >= 4.5:
        performance_text = "Outstanding Performance"
        performance_color = colors.HexColor('#10B981')
    elif overall_avg >= 4.0:
        performance_text = "Very Satisfactory Performance"
        performance_color = colors.HexColor('#22C55E')
    elif overall_avg >= 3.5:
        performance_text = "Satisfactory Performance"
        performance_color = colors.HexColor('#3B82F6')
    elif overall_avg >= 3.0:
        performance_text = "Fair Performance"
        performance_color = colors.HexColor('#F59E0B')
    else:
        performance_text = "Needs Improvement"
        performance_color = colors.HexColor('#EF4444')
    
    perf_summary = [
        ['Overall Rating', f"{overall_avg:.2f} / 5.00", performance_text],
    ]
    
    perf_table = Table(perf_summary, colWidths=[2*inch, 1.8*inch, 2.7*inch])
    perf_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BACKGROUND', (1, 0), (1, -1), colors.HexColor('#F3F4F6')),
        ('BACKGROUND', (2, 0), (2, -1), performance_color),
        ('TEXTCOLOR', (2, 0), (2, -1), colors.white),
        ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor('#E5E7EB')),
    ]))
    elements.append(perf_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Key Performance Indicators
    elements.append(Paragraph("2. Key Performance Indicators", heading_style))
    
    kpi_data = [
        ['Performance Area', 'Rating', 'Status'],
        ['A. Commitment to Teaching', f"{aggregates['avg_commitment']:.2f}" if aggregates['avg_commitment'] else 'N/A', 
         'Excellent' if (aggregates['avg_commitment'] or 0) >= 4.0 else 'Good' if (aggregates['avg_commitment'] or 0) >= 3.5 else 'Fair'],
        ['B. Knowledge of Subject', f"{aggregates['avg_knowledge']:.2f}" if aggregates['avg_knowledge'] else 'N/A',
         'Excellent' if (aggregates['avg_knowledge'] or 0) >= 4.0 else 'Good' if (aggregates['avg_knowledge'] or 0) >= 3.5 else 'Fair'],
        ['C. Teaching Strategies', f"{aggregates['avg_learning']:.2f}" if aggregates['avg_learning'] else 'N/A',
         'Excellent' if (aggregates['avg_learning'] or 0) >= 4.0 else 'Good' if (aggregates['avg_learning'] or 0) >= 3.5 else 'Fair'],
        ['D. Management of Learning', f"{aggregates['avg_management']:.2f}" if aggregates['avg_management'] else 'N/A',
         'Excellent' if (aggregates['avg_management'] or 0) >= 4.0 else 'Good' if (aggregates['avg_management'] or 0) >= 3.5 else 'Fair'],
        ['E. Feedback & Communication', f"{aggregates['avg_feedback_comm']:.2f}" if aggregates['avg_feedback_comm'] else 'N/A',
         'Excellent' if (aggregates['avg_feedback_comm'] or 0) >= 4.0 else 'Good' if (aggregates['avg_feedback_comm'] or 0) >= 3.5 else 'Fair'],
    ]
    
    kpi_table = Table(kpi_data, colWidths=[3.2*inch, 1.5*inch, 1.8*inch])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8E1B1B')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 1), (1, -1), 'CENTER'),
        ('ALIGN', (2, 1), (2, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F9FAFB')]),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Student Sentiment Analysis
    elements.append(Paragraph("3. AI-Powered Sentiment Analysis", heading_style))
    
    emotion_counts = {'joy': 0, 'satisfaction': 0, 'acceptance': 0, 'boredom': 0, 'disappointment': 0}
    for field in ['emotion_suggested_changes', 'emotion_best_aspect', 'emotion_least_aspect', 'emotion_further_comments']:
        field_counts = feedback_qs.values(field).annotate(count=Count(field))
        for item in field_counts:
            emotion = item[field]
            if emotion and emotion in emotion_counts:
                emotion_counts[emotion] += item['count']
    
    total_emotions = sum(emotion_counts.values())
    if total_emotions > 0:
        # Group emotions
        positive = emotion_counts['joy'] + emotion_counts['satisfaction']
        neutral = emotion_counts['acceptance']
        negative = emotion_counts['boredom'] + emotion_counts['disappointment']
        
        sentiment_data = [
            ['Sentiment Category', 'Count', 'Percentage', 'Interpretation'],
            ['Positive (Joy + Satisfaction)', str(positive), 
             f"{(positive/total_emotions*100):.1f}%",
             'Students express enthusiasm and contentment'],
            ['Neutral (Acceptance)', str(neutral), 
             f"{(neutral/total_emotions*100):.1f}%",
             'Students show moderate engagement'],
            ['Negative (Boredom + Disappointment)', str(negative), 
             f"{(negative/total_emotions*100):.1f}%",
             'Areas requiring attention and improvement'],
        ]
        
        sentiment_table = Table(sentiment_data, colWidths=[1.8*inch, 0.9*inch, 1.2*inch, 2.6*inch])
        sentiment_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8E1B1B')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (2, -1), 'CENTER'),
            ('ALIGN', (3, 0), (3, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F9FAFB')]),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(sentiment_table)
        elements.append(Spacer(1, 0.1*inch))
        
        # Sentiment interpretation
        pos_percent = (positive/total_emotions*100)
        if pos_percent >= 70:
            sent_interp = "Overwhelmingly positive student sentiment indicates strong teaching effectiveness."
        elif pos_percent >= 50:
            sent_interp = "Generally positive feedback with room for enhancement in specific areas."
        elif pos_percent >= 30:
            sent_interp = "Mixed feedback suggests need for targeted improvements in teaching methods."
        else:
            sent_interp = "Significant concerns identified; immediate action recommended to address student needs."
        
        elements.append(Paragraph(f"<b>Analysis:</b> {sent_interp}", normal_style))
        elements.append(Spacer(1, 0.15*inch))
        
        # Strengths and Areas for Improvement
        elements.append(Paragraph("4. Key Findings", heading_style))
        
        # Calculate strengths (ratings >= 4.0)
        strengths = []
        areas_improvement = []
        
        metrics = [
            ('Sensitivity to students', aggregates['avg_commitment']),
            ('Course content integration', aggregates['avg_integration']),
            ('Availability for consultation', aggregates['avg_availability']),
            ('Subject mastery', aggregates['avg_knowledge']),
            ('Practical application', aggregates['avg_practical']),
            ('Teaching strategies', aggregates['avg_learning']),
            ('Student autonomy development', aggregates['avg_autonomy']),
            ('Class discussion facilitation', aggregates['avg_discussion']),
            ('Clear communication', aggregates['avg_feedback_comm']),
            ('Timely feedback provision', aggregates['avg_timely']),
        ]
        
        for metric, value in metrics:
            if value and value >= 4.0:
                strengths.append(f"• {metric}: {value:.2f}/5.00")
            elif value and value < 3.5:
                areas_improvement.append(f"• {metric}: {value:.2f}/5.00")
        
        if strengths:
            elements.append(Paragraph("<b>Strengths:</b>", subheading_style))
            for strength in strengths[:5]:  # Top 5
                elements.append(Paragraph(strength, normal_style))
            elements.append(Spacer(1, 0.1*inch))
        
        if areas_improvement:
            elements.append(Paragraph("<b>Areas for Improvement:</b>", subheading_style))
            for area in areas_improvement[:5]:  # Top 5
                elements.append(Paragraph(area, normal_style))
            elements.append(Spacer(1, 0.15*inch))
        
        # Representative Student Comments
        elements.append(Paragraph("5. Student Feedback Highlights", heading_style))
        
        # Get a mix of positive and constructive comments
        positive_comments = []
        improvement_comments = []
        
        for fb in feedback_qs.select_related('student', 'course_assignment__course'):
            if fb.best_teaching_aspect and len(fb.best_teaching_aspect) > 20:
                positive_comments.append(fb.best_teaching_aspect)
            if fb.suggested_changes and len(fb.suggested_changes) > 20:
                improvement_comments.append(fb.suggested_changes)
            
            if len(positive_comments) >= 3 and len(improvement_comments) >= 3:
                break
        
        if positive_comments:
            elements.append(Paragraph("<b>What Students Appreciate:</b>", subheading_style))
            for i, comment in enumerate(positive_comments[:3], 1):
                # Truncate long comments
                display_comment = comment[:250] + "..." if len(comment) > 250 else comment
                elements.append(Paragraph(f"{i}. \"{display_comment}\"", 
                    ParagraphStyle('CommentStyle', parent=normal_style, leftIndent=15, fontSize=9, 
                                  textColor=colors.HexColor('#374151'), fontStyle='italic')))
                elements.append(Spacer(1, 0.08*inch))
        
        if improvement_comments:
            elements.append(Paragraph("<b>Suggestions for Enhancement:</b>", subheading_style))
            for i, comment in enumerate(improvement_comments[:3], 1):
                display_comment = comment[:250] + "..." if len(comment) > 250 else comment
                elements.append(Paragraph(f"{i}. \"{display_comment}\"", 
                    ParagraphStyle('CommentStyle', parent=normal_style, leftIndent=15, fontSize=9,
                                  textColor=colors.HexColor('#374151'), fontStyle='italic')))
                elements.append(Spacer(1, 0.08*inch))
        
        elements.append(Spacer(1, 0.1*inch))
        
        # Recommendations
        elements.append(Paragraph("6. Recommendations", heading_style))
        
        recommendations = []
        if overall_avg >= 4.0:
            recommendations.append("• Continue current teaching practices that are yielding positive results")
            recommendations.append("• Share best practices with other faculty members")
        
        if (aggregates['avg_feedback_comm'] or 0) < 3.5:
            recommendations.append("• Enhance communication clarity in course instructions and expectations")
        
        if (aggregates['avg_timely'] or 0) < 3.5:
            recommendations.append("• Improve turnaround time for assignment feedback and grading")
        
        if (aggregates['avg_discussion'] or 0) < 3.5:
            recommendations.append("• Foster more interactive classroom discussions and student participation")
        
        if negative > positive if total_emotions > 0 else False:
            recommendations.append("• Address student concerns through one-on-one consultations")
            recommendations.append("• Review and adjust teaching methodologies based on student feedback")
        
        if not recommendations:
            recommendations.append("• Maintain excellent teaching standards")
            recommendations.append("• Continue engaging with students for continuous improvement")
        
        for rec in recommendations:
            elements.append(Paragraph(rec, normal_style))
            elements.append(Spacer(1, 0.05*inch))
        
        elements.append(Spacer(1, 0.15*inch))
        
        # Footer note
        elements.append(Paragraph(
            "<i>This report was generated using AI-powered sentiment analysis to provide comprehensive insights into teaching effectiveness. "
            "The analysis combines quantitative ratings with qualitative emotional assessment of student feedback.</i>",
            ParagraphStyle('FooterNote', parent=normal_style, fontSize=8, textColor=colors.HexColor('#6B7280'), 
                          alignment=TA_JUSTIFY, leading=11)
        ))
        
        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer